modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      follow_redirects: true
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      preferred_ip_protocol: "ip4"
  tcp_connect:
    prober: tcp
    timeout: 3s
    tcp:
      preferred_ip_protocol: "ip4"
  dns_udp:
    prober: dns
    timeout: 3s
    dns:
      query_name: "example.com"
      query_type: "A"
      transport_protocol: "udp"
  icmp_ping:
    prober: icmp
    timeout: 3s
    icmp:
      preferred_ip_protocol: "ip4"
